# Generated by Django 2.2.1 on 2019-07-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0002_auto_20190703_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='passcet_emailcode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
