# Generated by Django 2.2.1 on 2019-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0003_passcet_emailcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcet_emailcode',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
