# Generated by Django 2.2.1 on 2019-07-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0004_passcet_emailcode_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcet_user',
            name='leavel',
            field=models.IntegerField(default=0),
        ),
    ]
