# Generated by Django 2.2.1 on 2019-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0005_passcet_user_leavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcet_user',
            name='lastimei',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='passcet_user',
            name='logintime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passcet_user',
            name='registertime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passcet_user',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
