# Generated by Django 2.2.1 on 2019-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0006_auto_20190712_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcet_user',
            name='img_md5',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
