# Generated by Django 2.2.1 on 2019-08-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0007_passcet_user_img_md5'),
    ]

    operations = [
        migrations.CreateModel(
            name='passcet_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('ph_en', models.CharField(max_length=128)),
                ('ph_am', models.CharField(max_length=128)),
                ('ph_en_mp3', models.CharField(max_length=128)),
                ('ph_am_mp3', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('sentence', models.TextField()),
                ('cet4', models.TextField()),
                ('cet6', models.TextField()),
            ],
        ),
    ]
