# Generated by Django 2.2.1 on 2019-08-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0008_passcet_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcet_word',
            name='cet4',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='passcet_word',
            name='cet6',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='passcet_word',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='passcet_word',
            name='ph_am',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='passcet_word',
            name='ph_am_mp3',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='passcet_word',
            name='ph_en',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='passcet_word',
            name='ph_en_mp3',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='passcet_word',
            name='sentence',
            field=models.TextField(default=0),
        ),
    ]
