# Generated by Django 2.2.1 on 2019-08-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0009_auto_20190810_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='passcet_glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=64)),
                ('word', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=128)),
            ],
        ),
    ]
