# Generated by Django 2.2.1 on 2019-08-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0010_passcet_glossary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcet_glossary',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
