# Generated by Django 2.2.1 on 2019-09-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0012_passcet_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='passcet_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('learningtime', models.IntegerField()),
                ('datetime', models.IntegerField()),
            ],
        ),
    ]
