# Generated by Django 2.2.1 on 2019-09-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0014_paccet_ranklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paccet_ranklist',
            new_name='passcet_ranklist',
        ),
    ]
