# Generated by Django 2.2.1 on 2019-11-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0015_auto_20190910_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='passcet_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=-1)),
                ('email', models.CharField(default=-1, max_length=128)),
                ('feedback', models.TextField(max_length=256)),
            ],
        ),
    ]
