# Generated by Django 2.2.1 on 2019-11-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0017_passcet_feedback_ischecked'),
    ]

    operations = [
        migrations.CreateModel(
            name='passcet_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemtype', models.IntegerField()),
                ('problem', models.TextField()),
                ('answer', models.TextField()),
                ('source', models.CharField(default='来源于网络', max_length=256)),
            ],
        ),
    ]
