# Generated by Django 2.2.1 on 2019-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcet', '0018_passcet_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcet_paper',
            name='cetype',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passcet_paper',
            name='year',
            field=models.TextField(default=0),
        ),
    ]
